<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-01T14:33:01 IST" name="Suite" finished-at="2023-12-01T14:33:15 IST" duration-ms="13723">
    <groups>
    </groups>
    <test started-at="2023-12-01T14:33:01 IST" name="Test" finished-at="2023-12-01T14:33:15 IST" duration-ms="13723">
      <class name="com.automation.businesscomponents.TestMe">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.automation.businesscomponents.TestMe@5a5338df]" started-at="2023-12-01T14:32:59 IST" name="setUp" finished-at="2023-12-01T14:33:01 IST" duration-ms="1792" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="quite()[pri:0, instance:com.automation.businesscomponents.TestMe@5a5338df]" started-at="2023-12-01T14:33:15 IST" name="quite" finished-at="2023-12-01T14:33:15 IST" duration-ms="519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- com.automation.businesscomponents.TestMe -->
      <class name="com.automation.businesscomponents.Login">
        <test-method signature="swagLabNavigation()[pri:0, instance:com.automation.businesscomponents.Login@7db0565c]" started-at="2023-12-01T14:33:01 IST" name="swagLabNavigation" finished-at="2023-12-01T14:33:03 IST" duration-ms="1719" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- swagLabNavigation -->
        <test-method signature="login()[pri:1, instance:com.automation.businesscomponents.Login@7db0565c]" started-at="2023-12-01T14:33:03 IST" name="login" finished-at="2023-12-01T14:33:15 IST" duration-ms="11959" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Testng test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Testng test failed
at org.testng.Assert.fail(Assert.java:111)
at com.automation.base.LoginBase.loginSwag(LoginBase.java:38)
at com.automation.businesscomponents.Login.login(Login.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- com.automation.businesscomponents.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
